name: Multi-Platform Build

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.11"
        cache: 'pip'
        cache-dependency-path: requirements.txt

    # 平台专用设置
    - name: Platform Setup
      run: |
        case "${{ runner.os }}" in
          "Windows")
            pip install --retries 3 pyinstaller==5.13.0
            ;;
          "Linux")
            sudo apt-get update
            sudo apt-get install -y patchelf binutils
            pip install pyinstaller==5.13.0
            ;;
          "macOS")
            brew install libffi
            pip install py2app==0.28.6
            export LDFLAGS="-L$(brew --prefix libffi)/lib"
            export CPPFLAGS="-I$(brew --prefix libffi)/include"
            ;;
        esac

    - name: Build Executable
      timeout-minutes: 20
      shell: bash
      run: |
        case "${{ runner.os }}" in
          "Windows")
            pyinstaller --onefile --icon=github-mark.png \
              --uac-admin --add-data="hooks/*;hooks" \
              --hidden-import=concurrent.futures \
              GitHubAccelerator.py -n GitHubAccelerator.exe
            ;;
          "Linux")
            pyinstaller --onefile --add-data="hooks/*:hooks" \
              --hidden-import=concurrent.futures \
              --clean GitHubAccelerator.py -n GitHubAccelerator
            strip dist/GitHubAccelerator
            ;;
          "macOS")
            # 动态生成必要文件
            mkdir -p icons.iconset
            sips -z 512 512 github-mark.png --out icons.iconset/icon_512x512.png
            iconutil -c icns icons.iconset -o github-mark.icns 2>/dev/null || true
            
            cat > setup.py <<EOL
            from setuptools import setup
            APP = ['GitHubAccelerator.py']
            DATA_FILES = ['hooks', 'github-mark.png']
            OPTIONS = {'iconfile': 'github-mark.icns'}
            setup(app=APP, data_files=DATA_FILES, options={'py2app': OPTIONS}, setup_requires=['py2app'])
            EOL
            
            python setup.py py2app
            sudo spctl --master-disable
            ;;
        esac

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GitHubAccelerator-${{ runner.os }}
        path: |
          ${{ 
            contains(runner.os, 'macOS') && 'dist/GitHubAccelerator.app' || 
            format('dist/GitHubAccelerator{0}', contains(runner.os, 'Windows') && '.exe' || '')
          }}
        retention-days: 3

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: GitHubAccelerator-*
        path: release

    - uses: softprops/action-gh-release@v1
      with:
        files: |
          release/**/*
