jobs:
  linux-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev patchelf binutils
    
    - name: Build Linux Binary
      run: |
        sed -i 's/\r$//' build_linux.sh  # 修复Windows换行符问题
        chmod +x build_linux.sh
        ./build_linux.sh

  macos-build:
    runs-on: macos-13
    env:
      KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Import Certificate
      run: |
        echo ${{ secrets.MAC_CERT }} | base64 -D > dev_cert.p12
        security create-keychain -p $KEYCHAIN_PWD build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p $KEYCHAIN_PWD build.keychain
        security import dev_cert.p12 -k build.keychain -P ${{ secrets.CERT_PWD }} -T /usr/bin/codesign
    
    - name: Build with Sign
      run: |
        chmod +x build_mac.sh
        ./build_mac.sh
        codesign --deep --force --verify --verbose --sign "Developer ID" dist/GitHubAccelerator
